baseURL = "https://tlgs.dev"
title = "ars longa"

[frontmatter]
  date = [":filename", ":default"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

  [markup.highlight]
    style = "pygments"
