baseURL = "https://tlgs.dev"
title = "ars longa"
enableRobotsTXT = true
disableKinds = ["taxonomy", "term"]

[frontmatter]
date = [":filename", ":default"]

[markup]
goldmark.renderer.unsafe = true
highlight.style = "pygments"
